// Package swagger provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package swagger

import (
	"fmt"
	"net/http"

	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
)

// Defines values for PostFilterParamsOrder.
const (
	PostFilterParamsOrderAsc  PostFilterParamsOrder = "asc"
	PostFilterParamsOrderDesc PostFilterParamsOrder = "desc"
)

// Defines values for PostFulltextParamsOrder.
const (
	PostFulltextParamsOrderAsc  PostFulltextParamsOrder = "asc"
	PostFulltextParamsOrderDesc PostFulltextParamsOrder = "desc"
)

// Event the primary unit of the nostr protocol, a self-signed JSON object that derives its id from a canonical ordered array
type Event struct {
	Content   *string     `json:"content,omitempty"`
	CreatedAt *int        `json:"created_at,omitempty"`
	Id        *string     `json:"id,omitempty"`
	Kind      *int        `json:"kind,omitempty"`
	Pubkey    *string     `json:"pubkey,omitempty"`
	Sig       *string     `json:"sig,omitempty"`
	Tags      *[][]string `json:"tags,omitempty"`
}

// Filter a simple filter structure used in request bodies to specify the parameters of a simple index search
type Filter struct {
	// Authors lists of hex encoded values, primarily for event Ids and public keys
	Authors *Ids      `json:"authors,omitempty"`
	Kinds   *[]int    `json:"kinds,omitempty"`
	Tags    *[]string `json:"tags,omitempty"`
}

// Ids lists of hex encoded values, primarily for event Ids and public keys
type Ids = []string

// AdminAuth defines model for AdminAuth.
type AdminAuth = string

// AlwaysAuth defines model for AlwaysAuth.
type AlwaysAuth = string

// Auth defines model for Auth.
type Auth = string

// Upgrade defines model for Upgrade.
type Upgrade = string

// GetBackupParams defines parameters for GetBackup.
type GetBackupParams struct {
	// Authorization NIP-98 "Nostr <token>" or JWT "Bearer <token>" for users on their own data (mandatory)
	Authorization AlwaysAuth `json:"Authorization"`
}

// GetEventIdParams defines parameters for GetEventId.
type GetEventIdParams struct {
	// Authorization NIP-98 "Nostr <token>" or JWT "Bearer <token>" (required as per relay configuration)
	Authorization *Auth `json:"Authorization,omitempty"`
}

// PostEventsParams defines parameters for PostEvents.
type PostEventsParams struct {
	// Authorization NIP-98 "Nostr <token>" or JWT "Bearer <token>" (required as per relay configuration)
	Authorization *Auth `json:"Authorization,omitempty"`
}

// PostExportParams defines parameters for PostExport.
type PostExportParams struct {
	// Authorization NIP-98 "Nostr <token>" or JWT "Bearer <token>" for administrators (mandatory)
	Authorization AdminAuth `json:"Authorization"`
}

// PostFilterParams defines parameters for PostFilter.
type PostFilterParams struct {
	// Since only return events equal or greater than this unix timestamp
	Since *int `form:"since,omitempty" json:"since,omitempty"`

	// Until only return events equal or lesser than this unix timestamp
	Until *int `form:"until,omitempty" json:"until,omitempty"`

	// Limit only return this many events from the starting point in the set order. if unset, there is no limit
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Order return the results sorted by created_at in this direction
	Order *PostFilterParamsOrder `form:"order,omitempty" json:"order,omitempty"`

	// Authorization NIP-98 "Nostr <token>" or JWT "Bearer <token>" (required as per relay configuration)
	Authorization *Auth `json:"Authorization,omitempty"`
}

// PostFilterParamsOrder defines parameters for PostFilter.
type PostFilterParamsOrder string

// PostFulltextParams defines parameters for PostFulltext.
type PostFulltextParams struct {
	// Search full text search based on a full text search index
	Search *int `form:"search,omitempty" json:"search,omitempty"`

	// Since only return events equal or greater than this unix timestamp
	Since *int `form:"since,omitempty" json:"since,omitempty"`

	// Until only return events equal or lesser than this unix timestamp
	Until *int `form:"until,omitempty" json:"until,omitempty"`

	// Limit only return this many events from the starting point in the set order. if unset, there is no limit
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Order return the results sorted by created_at in this direction
	Order *PostFulltextParamsOrder `form:"order,omitempty" json:"order,omitempty"`

	// Authorization NIP-98 "Nostr <token>" or JWT "Bearer <token>" (required as per relay configuration)
	Authorization *Auth `json:"Authorization,omitempty"`
}

// PostFulltextParamsOrder defines parameters for PostFulltext.
type PostFulltextParamsOrder string

// PostImportParams defines parameters for PostImport.
type PostImportParams struct {
	// Authorization NIP-98 "Nostr <token>" or JWT "Bearer <token>" for administrators (mandatory)
	Authorization AdminAuth `json:"Authorization"`
}

// GetNukeParams defines parameters for GetNuke.
type GetNukeParams struct {
	// Authorization NIP-98 "Nostr <token>" or JWT "Bearer <token>" for administrators (mandatory)
	Authorization AdminAuth `json:"Authorization"`
}

// PostRelayParams defines parameters for PostRelay.
type PostRelayParams struct {
	// Authorization NIP-98 "Nostr <token>" or JWT "Bearer <token>" (required as per relay configuration)
	Authorization *Auth `json:"Authorization,omitempty"`
}

// GetShutdownParams defines parameters for GetShutdown.
type GetShutdownParams struct {
	// Authorization NIP-98 "Nostr <token>" or JWT "Bearer <token>" for administrators (mandatory)
	Authorization AdminAuth `json:"Authorization"`
}

// PostStoreParams defines parameters for PostStore.
type PostStoreParams struct {
	// Authorization NIP-98 "Nostr <token>" or JWT "Bearer <token>" (required as per relay configuration)
	Authorization *Auth `json:"Authorization,omitempty"`
}

// PostSubscribeParams defines parameters for PostSubscribe.
type PostSubscribeParams struct {
	// Authorization NIP-98 "Nostr <token>" or JWT "Bearer <token>" (required as per relay configuration)
	Authorization *Auth `json:"Authorization,omitempty"`

	// Upgrade websocket upgrade
	Upgrade Upgrade `json:"Upgrade"`
}

// PostEventsJSONRequestBody defines body for PostEvents for application/json ContentType.
type PostEventsJSONRequestBody = Ids

// PostExportJSONRequestBody defines body for PostExport for application/json ContentType.
type PostExportJSONRequestBody = Filter

// PostFilterJSONRequestBody defines body for PostFilter for application/json ContentType.
type PostFilterJSONRequestBody = Filter

// PostFulltextJSONRequestBody defines body for PostFulltext for application/json ContentType.
type PostFulltextJSONRequestBody = Filter

// PostRelayJSONRequestBody defines body for PostRelay for application/json ContentType.
type PostRelayJSONRequestBody = Event

// PostStoreJSONRequestBody defines body for PostStore for application/json ContentType.
type PostStoreJSONRequestBody = Event

// PostSubscribeJSONRequestBody defines body for PostSubscribe for application/json ContentType.
type PostSubscribeJSONRequestBody = Filter

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// export events all events of the must-be-authed user in line structured JSON (.jsonl)
	// (GET /backup)
	GetBackup(w http.ResponseWriter, r *http.Request, params GetBackupParams)
	// return a document associated with the requested endpoint
	// (GET /documentation/{endpoint})
	GetDocumentationEndpoint(w http.ResponseWriter, r *http.Request, endpoint string)
	// fetch one event by ID
	// (GET /event/{id})
	GetEventId(w http.ResponseWriter, r *http.Request, id string, params GetEventIdParams)
	// request multiple events by event ID
	// (POST /events)
	PostEvents(w http.ResponseWriter, r *http.Request, params PostEventsParams)
	// export events in line structured JSON (.jsonl)
	// (POST /export)
	PostExport(w http.ResponseWriter, r *http.Request, params PostExportParams)
	// search for events by various matching parameters, and return a list of matching event Ids sorted by the requested order of created_at timestamps
	// (POST /filter)
	PostFilter(w http.ResponseWriter, r *http.Request, params PostFilterParams)
	// search for events by various matching parameters, and return a list of matching event Ids sorted by the requested order of created_at timestamps
	// (POST /fulltext)
	PostFulltext(w http.ResponseWriter, r *http.Request, params PostFulltextParams)
	// import events in line structured JSON (.jsonl)
	// (POST /import)
	PostImport(w http.ResponseWriter, r *http.Request, params PostImportParams)
	// delete all events in event store
	// (GET /nuke)
	GetNuke(w http.ResponseWriter, r *http.Request, params GetNukeParams)
	// lists conditions for authentication requirement on all http endpoints
	// (GET /permissions)
	GetPermissions(w http.ResponseWriter, r *http.Request)
	// read the terms of service/policy document for this relay
	// (GET /policy)
	GetPolicy(w http.ResponseWriter, r *http.Request)
	// sends an event to subscribers but does not store event
	// (POST /relay)
	PostRelay(w http.ResponseWriter, r *http.Request, params PostRelayParams)
	// shut down the relay
	// (GET /shutdown)
	GetShutdown(w http.ResponseWriter, r *http.Request, params GetShutdownParams)
	// stores an event on the relay and sends it to subscribers
	// (POST /store)
	PostStore(w http.ResponseWriter, r *http.Request, params PostStoreParams)
	// Same as filter except only for newly published events, only event Ids are sent, requires websocket connection
	// (POST /subscribe)
	PostSubscribe(w http.ResponseWriter, r *http.Request, params PostSubscribeParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetBackup operation middleware
func (siw *ServerInterfaceWrapper) GetBackup(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBackupParams

	headers := r.Header

	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization AlwaysAuth
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Authorization", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Authorization", Err: err})
			return
		}

		params.Authorization = Authorization

	} else {
		err = fmt.Errorf("Header parameter Authorization is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Authorization", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBackup(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDocumentationEndpoint operation middleware
func (siw *ServerInterfaceWrapper) GetDocumentationEndpoint(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "endpoint" -------------
	var endpoint string

	err = runtime.BindStyledParameterWithOptions("simple", "endpoint", mux.Vars(r)["endpoint"], &endpoint, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "endpoint", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDocumentationEndpoint(w, r, endpoint)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventId operation middleware
func (siw *ServerInterfaceWrapper) GetEventId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventIdParams

	headers := r.Header

	// ------------- Optional header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Auth
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Authorization", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Authorization", Err: err})
			return
		}

		params.Authorization = &Authorization

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventId(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEvents operation middleware
func (siw *ServerInterfaceWrapper) PostEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostEventsParams

	headers := r.Header

	// ------------- Optional header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Auth
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Authorization", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Authorization", Err: err})
			return
		}

		params.Authorization = &Authorization

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostExport operation middleware
func (siw *ServerInterfaceWrapper) PostExport(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostExportParams

	headers := r.Header

	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization AdminAuth
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Authorization", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Authorization", Err: err})
			return
		}

		params.Authorization = Authorization

	} else {
		err = fmt.Errorf("Header parameter Authorization is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Authorization", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostExport(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostFilter operation middleware
func (siw *ServerInterfaceWrapper) PostFilter(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostFilterParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	// ------------- Optional query parameter "until" -------------

	err = runtime.BindQueryParameter("form", true, false, "until", r.URL.Query(), &params.Until)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "until", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Auth
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Authorization", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Authorization", Err: err})
			return
		}

		params.Authorization = &Authorization

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostFilter(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostFulltext operation middleware
func (siw *ServerInterfaceWrapper) PostFulltext(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostFulltextParams

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", r.URL.Query(), &params.Search)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	// ------------- Optional query parameter "until" -------------

	err = runtime.BindQueryParameter("form", true, false, "until", r.URL.Query(), &params.Until)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "until", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Auth
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Authorization", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Authorization", Err: err})
			return
		}

		params.Authorization = &Authorization

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostFulltext(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostImport operation middleware
func (siw *ServerInterfaceWrapper) PostImport(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostImportParams

	headers := r.Header

	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization AdminAuth
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Authorization", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Authorization", Err: err})
			return
		}

		params.Authorization = Authorization

	} else {
		err = fmt.Errorf("Header parameter Authorization is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Authorization", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostImport(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNuke operation middleware
func (siw *ServerInterfaceWrapper) GetNuke(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNukeParams

	headers := r.Header

	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization AdminAuth
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Authorization", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Authorization", Err: err})
			return
		}

		params.Authorization = Authorization

	} else {
		err = fmt.Errorf("Header parameter Authorization is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Authorization", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNuke(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPermissions operation middleware
func (siw *ServerInterfaceWrapper) GetPermissions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPermissions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPolicy operation middleware
func (siw *ServerInterfaceWrapper) GetPolicy(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPolicy(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRelay operation middleware
func (siw *ServerInterfaceWrapper) PostRelay(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostRelayParams

	headers := r.Header

	// ------------- Optional header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Auth
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Authorization", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Authorization", Err: err})
			return
		}

		params.Authorization = &Authorization

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRelay(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetShutdown operation middleware
func (siw *ServerInterfaceWrapper) GetShutdown(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetShutdownParams

	headers := r.Header

	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization AdminAuth
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Authorization", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Authorization", Err: err})
			return
		}

		params.Authorization = Authorization

	} else {
		err = fmt.Errorf("Header parameter Authorization is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Authorization", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetShutdown(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostStore operation middleware
func (siw *ServerInterfaceWrapper) PostStore(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostStoreParams

	headers := r.Header

	// ------------- Optional header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Auth
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Authorization", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Authorization", Err: err})
			return
		}

		params.Authorization = &Authorization

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostStore(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostSubscribe operation middleware
func (siw *ServerInterfaceWrapper) PostSubscribe(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostSubscribeParams

	headers := r.Header

	// ------------- Optional header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Auth
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Authorization", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Authorization", Err: err})
			return
		}

		params.Authorization = &Authorization

	}

	// ------------- Required header parameter "Upgrade" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Upgrade")]; found {
		var Upgrade Upgrade
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Upgrade", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Upgrade", valueList[0], &Upgrade, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Upgrade", Err: err})
			return
		}

		params.Upgrade = Upgrade

	} else {
		err = fmt.Errorf("Header parameter Upgrade is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Upgrade", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSubscribe(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/backup", wrapper.GetBackup).Methods("GET")

	r.HandleFunc(options.BaseURL+"/documentation/{endpoint}", wrapper.GetDocumentationEndpoint).Methods("GET")

	r.HandleFunc(options.BaseURL+"/event/{id}", wrapper.GetEventId).Methods("GET")

	r.HandleFunc(options.BaseURL+"/events", wrapper.PostEvents).Methods("POST")

	r.HandleFunc(options.BaseURL+"/export", wrapper.PostExport).Methods("POST")

	r.HandleFunc(options.BaseURL+"/filter", wrapper.PostFilter).Methods("POST")

	r.HandleFunc(options.BaseURL+"/fulltext", wrapper.PostFulltext).Methods("POST")

	r.HandleFunc(options.BaseURL+"/import", wrapper.PostImport).Methods("POST")

	r.HandleFunc(options.BaseURL+"/nuke", wrapper.GetNuke).Methods("GET")

	r.HandleFunc(options.BaseURL+"/permissions", wrapper.GetPermissions).Methods("GET")

	r.HandleFunc(options.BaseURL+"/policy", wrapper.GetPolicy).Methods("GET")

	r.HandleFunc(options.BaseURL+"/relay", wrapper.PostRelay).Methods("POST")

	r.HandleFunc(options.BaseURL+"/shutdown", wrapper.GetShutdown).Methods("GET")

	r.HandleFunc(options.BaseURL+"/store", wrapper.PostStore).Methods("POST")

	r.HandleFunc(options.BaseURL+"/subscribe", wrapper.PostSubscribe).Methods("POST")

	return r
}
