= http authentication
:toc:

The nostr protocol includes an authentication mechanism based on nostr events and HTTP headers that you can read our local version here: link:98.adoc[nip-98]; however, there are numerous tools you might want to use to interact with HTTP listeners such as the simplified HTTP protocol described in link:../readme.adoc#simplified-nostr[the readme] which would permit the deployment of a relay with auth-controlled access, but be able to use tooling that can't be easily augmented to use link:98.adoc[nip-98], and use PEM encoded secrets that can be used with standards compliant JWT implementations.

The main use cases are for testing and administrative purposes, but it may also enable devices such as old/low-spec ebook readers' browsers to interact with nostr based document libraries such as Alexandria, for devices that can neither do websockets nor easily handle NIP-98 headers for paid/private document repositories.

HTTP versions of the protocol are not just about enabling devices that may not be able to do websockets, or be easily programmable even still to do NIP-98 authentication, they are also simpler and enable lowering the overhead caused by the use of sockets for simple request/response protocols that have no need to maintain liveness or store socket state information.

== JWT Authentication Registration Event

The simplest way to enable this for a nostr relay is to create a new event kind which allows a user to associate a JWT public key token with their nostr public key, and then the relay's access control mechanism can search for it and authorize using JWT in place of NIP-98 or NIP-42 websocket auth.

To make this mesh with the standard NIP-01 specification for indexing, the simplest way is to place the JWT public key in a `J` tag and then when a request is received with the JWT token, after it is decoded, the event tagged with this token can be found with a simple query and then the associated public key of the user that published the event with this token can be located.

So, the event structure is as follows:

[source,json]
----
{
  "id": "<event id>",
  "kind": 30050,
  "pubkey": "<user pubkey>",
  "created_at": 1234567890,
  "content": "",
  "tags": [
    ["J","<JWT .cert>","<alg>"]
  ],
  "sig": "<signature matching user pubkey>"
}
----

By publishing this event, with the JWT secret key, the user proves control of the JWT token and that it is equivalent as their own nsec for signing JWT signed HTTP requests in place of using the NIP-98 authentication.

NOTE: it should be possible to later also use this to assign other authentication mechanisms trust, should other mechanisms be usable for other environments that would otherwise not be able to work with nostr relays.

== JWT Authentication Protocol

In every respect, other than the different key/signature algorithm, and authentication event token encoding, this protocol is identical to NIP-98

This means that the JWT must include the HTTP method, the full URL of the request, and a base 10 encoded timestamp that is within 15 seconds of the server/relay current unix time:

The encoding should then be:

[source]
----
{
    "iss":"<hex pubkey of user>",
    "typ":"message",
    "sub":"http://example.com/path/to/endpoint",
    "alg":"ES256"
    "iat":1234567890,
}
----

The JWT token must then have a signature on this string, and that signature match the JWT token registered in the kind 30050.

An additional field `exp` can be present and will allow the client to generate one certificate and use it until the time specified (same as `iat` it is a decimal unix timestamp seconds).

== The Actual Authorization

Where the NIP-98 uses:

  Authorization: Nostr <base64 encoded auth event>

to comport with the standard for JWT:

  Authorization: Bearer <jwt.token.string>

The relay must be able to distinguish between the `Nostr` and `Bearer` sentinels in the header value for `Authorization` and then it can validate the JWT token, and then search for the JWT registration, and then use the associated nostr public key to check for permission to do whatever the POST (or QUERY) body specifies.